# Generated by Django 5.0.3 on 2024-04-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft_furniture_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='product',
            name='favorite',
        ),
        migrations.AddField(
            model_name='product',
            name='baskets',
            field=models.ManyToManyField(blank=True, null=True, related_name='basket_products', to='loft_furniture_app.basket'),
        ),
        migrations.AddField(
            model_name='product',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_products', to='loft_furniture_app.favorite'),
        ),
    ]
